### PR TITLE
Migrate serving operator to use knative.dev/serving-operator import path

### PR DESCRIPTION
**Pull request by trshafer**
I have broken this into two commits:

1. The manual changes I made.
2. The scripted changes I made.

Ran `sed -i 's@github.com/knative/serving-operator@knative.dev/serving-operator@g' $(find -name '*.go' | xargs grep github.com/knative/serving-operator | cut -d':' -f 1 | uniq)`

Related to https://github.com/knative/pkg/pull/489 and https://github.com/knative/serving/pull/4521

### CODE REVIEW

**Comment by mattmoor** [comment]
/lgtm
/assign @chaodaiG 

Needs to be coordinated with Prow changes.

**Comment by houshengbo** [comment]
@trshafer 
I have one question regarding the import change: if we add a new package github.com/knativeserving-operator/pkg/reconciler/knativeserving into the source code, are we able to use knative.dev/serving-operator/pkg/reconciler/knativeserving directly in the PR?

**Comment by trshafer** [comment]
@houshengbo yes I believe all of the imports for serving-operator will be `knative.dev/serving-operator` prefixed.

**Pull request merged**
