### PR TITLE
Remove all references to OLM.

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title. This is just unused stuff as of right now and will be or is already broken. Let's remove it from the repo for now and reintroduce as a conscious decision if necessary.

/assign @jcrossley3 
/assign @houshengbo

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Retrying to see if it's consistent. No idea yet how this would cause a breakage unless something's still relying on the "deploy" link.

/test pull-knative-serving-operator-integration-tests

**Comment by houshengbo** [comment]
@markusthoemmes Remember the sleep I removed. I used to bump into this constantly. After adding the KS verification, it turned out fine for a while. I hope it is just accidental.

**Comment by markusthoemmes** [comment]
@houshengbo passed this time round.

**Pull request merged**
