### PR TITLE
Remove includeOutboundIPRanges config from minikube

### PR DESCRIPTION
**Pull request by nak3**
## Proposed Changes

By https://github.com/knative/serving/pull/6597/
`istio.sidecar.includeOutboundIPRanges` is obsoleted.

This patch removes the config from minikube sample operator.

/lint

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by nak3** [comment]
I'm wondering if entire minikube-operator-example, but I just removed the config in this PR.

**Comment by k4leung4** [comment]
@trshafer @jcrossley3 can either of you remind me whats the purpose of this minikube-operator-example and how do we ensure that it is tested and up to date?

**Comment by jcrossley3** [comment]
@k4leung4 imo, the example doesn't belong in this repo -- it belongs in its own -- so I believe its existence in here is only temporary.

**Pull request merged**
