### PR TITLE
Fix OLM metadata for 0.11.0

### PR DESCRIPTION
**Pull request by aliok**
Fixes # 271

## Proposed Changes

* Fix the ALM examples in 0.11.0 CSV

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by k4leung4** [comment]
can you update the PR description to explain what was wrong and how you are fixing it?
looking at the change alone does not make it obvious what is happening.

**Comment by aliok** [comment]
@k4leung4 Definitely!

Just created an issue https://github.com/knative/serving-operator/issues/271

**Pull request merged**
