### PR TITLE
Remove auto-install of KS custom resource, fixes #119

### LINKED ISSUE #119: Remove auto-install logic
This is related to #39 but worth being in its own issue as it's a small part of the overall (expected) resolution, but an important piece to facilitate testing.

### PR DESCRIPTION
**Pull request by jcrossley3**
Fixes #119 

## Proposed Changes

* No longer automatically creating `KnativeServing` CR in `knative-serving` namespace
* User expected to create the CR to install knative-serving, in whatever desired namespace

**Release Note**

```release-note
It is no longer enough to simply deploy the operator to install `knative-serving`. The operator now passively watches for `KnativeServing` custom resources and deploys `knative-serving` into the namespace in which it is found.
```

### CODE REVIEW

**Comment by trshafer** [comment]
Should https://github.com/knative/serving-operator/blob/master/cmd/manager/kodata/serving_v1alpha1_knativeserving_cr.yaml and https://github.com/knative/serving-operator/blob/master/config/crds/serving_v1alpha1_knativeserving_cr.yaml be deleted?

Does this close #93?

**Comment by jcrossley3** [comment]
> Should https://github.com/knative/serving-operator/blob/master/cmd/manager/kodata/serving_v1alpha1_knativeserving_cr.yaml and https://github.com/knative/serving-operator/blob/master/config/crds/serving_v1alpha1_knativeserving_cr.yaml be deleted?

The former, certainly. The latter is still referenced in the README as a convenient way to install knative-serving, but I suppose we could put some yaml in the README?

> Does this close #93?

I don't really understand #93, tbh. :smile:

**Comment by houshengbo** [comment]
@trshafer TRUE. we need to delete existing KS check for now, and add new ones as in https://github.com/knative/serving-operator/pull/108

**Comment by houshengbo** [comment]
Plz remove the logic here: https://github.com/knative/serving-operator/blob/master/test/e2e/knativeservingdeployment_test.go#L38, and the other test file https://github.com/knative/serving-operator/blob/master/test/e2e/knativeserving_test.go. @jcrossley3

**Comment by jcrossley3** [comment]
> Plz remove the logic here: https://github.com/knative/serving-operator/blob/master/test/e2e/knativeservingdeployment_test.go#L38, and the other test file https://github.com/knative/serving-operator/blob/master/test/e2e/knativeserving_test.go. @jcrossley3

Done

**Comment by trshafer** [comment]
> > Should https://github.com/knative/serving-operator/blob/master/cmd/manager/kodata/serving_v1alpha1_knativeserving_cr.yaml and https://github.com/knative/serving-operator/blob/master/config/crds/serving_v1alpha1_knativeserving_cr.yaml be deleted?
> 
> The former, certainly. The latter is still referenced in the README as a convenient way to install knative-serving, but I suppose we could put some yaml in the README?

I think it would be better to remove the example CR from config. I don't think people would think to look there for an example. I think the `Readme` or in a `documentation/` or `example/` folder would be better.

> 
> > Does this close #93?
> 
> I don't really understand #93, tbh.

If I first install the KnativeServing CRD, then create a pretty simple KnativeServing CR myself. When I deploy the Operator, the KnativeServing CR that I created is updated with the example KnativeServing CR configuration.

**Comment by jcrossley3** [comment]
> If I first install the KnativeServing CRD, then create a pretty simple KnativeServing CR myself. When I deploy the Operator, the KnativeServing CR that I created is updated with the example KnativeServing CR configuration.

Ah! Yeah, that logic is broken. It's not supposed to do anything if there's already a CR present. And yes, I expect this change would close #93 

I'll move the yaml in the file to the README.

**Comment by trshafer** [comment]
/hold
/lgtm

LGTM from me. Feel free to cancel the hold when you are comfortable with everybody else's review.

**Pull request merged**
