### PR TITLE
Update the year of the copyright to 2020 in the template

### PR DESCRIPTION
**Pull request by houshengbo**
## Proposed Changes

* As we move into the year of mouse, update the year to 2020 in the template.

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by markusthoemmes** [comment]
We don't usually do this in other repos. Is this required?

**Comment by houshengbo** [comment]
/hold
Let me do a confirmation about the change.

**Comment by houshengbo** [comment]
/hold cancel
@markusthoemmes You are correct. The source code should stay with the original, so only change the year in the template.

Here is some discussions: https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

In general, there are two type voices:
1. Stay with the year when the work is first published.
2. We CAN update a copyright year only if contributions are made to the work during that year.

**Comment by k4leung4** [comment]
/lgtm

it does seem we do this for serving and eventing
https://github.com/knative/serving/pull/6464
https://github.com/knative/eventing/pull/2359

**Pull request merged**
